FROM python:3.11-slim

WORKDIR /app

ENV PYTHONPATH=/app

COPY training/ training/
COPY data/ data/
COPY artifacts/ artifacts/


RUN pip install --no-cache-dir \
    numpy \
    pandas \
    scikit-multilearn \
    scikit-learn==1.7.0 \
    joblib \
    pyarrow \
    mlflow


CMD ["python", "training/model.py"]
